"""initial schema

Revision ID: 505c304da464
Revises: 
Create Date: 2026-03-01 12:27:42.194441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505c304da464'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('moving_time_seconds', sa.Integer(), nullable=True),
    sa.Column('elapsed_time_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('load', sa.Float(), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('avg_power', sa.Float(), nullable=True),
    sa.Column('normalized_power', sa.Float(), nullable=True),
    sa.Column('avg_pace', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_external_id'), ['external_id'], unique=True)

    op.create_table('fitness_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ctl', sa.Float(), nullable=True),
    sa.Column('atl', sa.Float(), nullable=True),
    sa.Column('tsb', sa.Float(), nullable=True),
    sa.Column('ramp_rate', sa.Float(), nullable=True),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_start_date', sa.Date(), nullable=True),
    sa.Column('plan_name', sa.String(length=256), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lon', sa.Float(), nullable=True),
    sa.Column('sleep_target_hours', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rows_synced', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_log_source'), ['source'], unique=False)

    op.create_table('wellness',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hrv_rmssd', sa.Float(), nullable=True),
    sa.Column('hrv_status', sa.String(length=20), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sleep_start', sa.String(length=30), nullable=True),
    sa.Column('sleep_end', sa.String(length=30), nullable=True),
    sa.Column('body_battery_high', sa.Integer(), nullable=True),
    sa.Column('body_battery_low', sa.Integer(), nullable=True),
    sa.Column('body_battery_most_recent', sa.Integer(), nullable=True),
    sa.Column('training_readiness', sa.Integer(), nullable=True),
    sa.Column('training_status', sa.String(length=30), nullable=True),
    sa.Column('endurance_score', sa.Float(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('avg_stress', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wellness')
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_log_source'))

    op.drop_table('sync_log')
    op.drop_table('settings')
    op.drop_table('fitness_metrics')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_external_id'))
        batch_op.drop_index(batch_op.f('ix_activities_date'))

    op.drop_table('activities')
    # ### end Alembic commands ###
